test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: laforge_staging
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: laforge_production
  username: root
  password: ''
